### ISSUE TITLE
The program is too slow

### ISSUE THREAD

**Issue by codingzzy** [DwangoMediaVillage/keras_compressor#5]
I find the program that it is processed by single thread(sinle core). how to make it processed by more thread or gpu

**Comment by cocuh** [comment]
Currently, this code does not support multi-thread because of development cost. Simple way to improve speed is to modify [layer-wised compression process](https://github.com/DwangoMediaVillage/keras_compressor/blob/722c7c0f84fe89f91a2f75a438635866badf7347/keras_compressor/compressor.py#L38) to make parallel. Pull requests are always welcome.

**Comment by mationai** [comment]
It's still running after 10 hrs on a 45MB model on a 2012 macbook pro. Is it normal? If so, how much longer will it be?

thanks.

Edit - Can ignore this, as ask in new issue.
